// PROJETOS/_ecommerce/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductsService } from '../services/products.service';


@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  

  constructor(
    
  ) { }

  ngOnInit() {
    
  }
}   
  


<div class="app-header">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      
      <a class="navbar-brand" href="#">Utilidades Cata-Vento</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse nav justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" [routerLink]="['/product']">Panelas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Serviços</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <nav class="navbar navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="#">
        
      </a>
    </div>
  </nav>
  
  <!-- Large button groups (default and split) -->
<!-- Large button groups (default and split) -->



<!-- As a link -->


<!-- As a heading -->
<!-- <nav class="navbar navbar-light bg-light">
  <div class="btn-group">
  <button class="btn btn-secondary btn-lg dropdown-toggle " type="button" data-bs-toggle="dropdown" aria-expanded="false">
  Panelas
</button>
<ul class="dropdown-menu">
  <li><a class="dropdown-item" href="#">Cadastrar</a></li>
  <li><a class="dropdown-item" [routerLink]="['/product']" >Consultar</a></li>
  <li><a class="dropdown-item" href="#">Estoque</a></li>
  <li><a class="dropdown-item" href="#">Pedido-Compra</a></li>
  </ul>
  </div>
</nav>
<nav class="navbar navbar-light bg-light">
<div class="btn-group">
<button class="btn btn-secondary btn-lg dropdown-toggle " type="button" data-bs-toggle="dropdown" aria-expanded="false">
Fogões
</button>
<ul class="dropdown-menu">
<li><a class="dropdown-item" href="#">Cadastrar</a></li>
<li><a class="dropdown-item" href="#">Consultar</a></li>
<li><a class="dropdown-item" href="#">Estoque</a></li>
<li><a class="dropdown-item" href="#">Pedido-Compra</a></li>
</ul>
</div>
</nav>

<nav class="navbar navbar-light bg-light">
<div class="btn-group">
<button class="btn btn-secondary btn-lg dropdown-toggle " type="button" data-bs-toggle="dropdown" aria-expanded="false">
Móveis
</button>
<ul class="dropdown-menu">
<li><a class="dropdown-item" href="#">Cadastrar</a></li>
<li><a class="dropdown-item" href="#">Consultar</a></li>
<li><a class="dropdown-item" href="#">Estoque</a></li>
<li><a class="dropdown-item" href="#">Pedido-Compra</a></li>
</ul>
</div>
</nav> -->
</div>

  
     
      
            
  <!-- Main Navigation -->
  <!--/ End Header -->

// PROJETOS/react-aula-react-aula-05/src/components/header/header.component.js
import React from 'react';
import { Link } from 'react-router-dom'

class Header extends React.Component{

    constructor(props){
        super(props)
        this.state = {}
        // console.log("props", props)
    }
    
    insideHeader(){
        console.log("Você chamou uma função do header.")
    }

    render(){
        return (
            <nav className="navbar navbar-expand-lg navbar-light bg-light">
                <a className="navbar-brand" href="#" onClick={this.props.onTitleClicked}>
                    {this.props.title}
                </a>
                <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse" id="navbarNav">
                    <ul className="navbar-nav">
                        <li className="nav-item">
                            <Link to="/" className="nav-link">
                                Home
                            </Link>
                        </li>
                        <li className="nav-item">
                            <Link to="/chats" className="nav-link">
                                Chats
                            </Link>
                        </li>
                    </ul>
                </div>
                {this.props.children}
            </nav>
        )
    }
}

export default Header;
